### ISSUE TITLE
Dockerfile/Source for kphoen/dark-converter

### ISSUE THREAD

**Issue by sfrank-mc** [K-Phoen/dark#59]
Hi,
We would like to extend the converter for our use-case.
Anyway we can find the sources anywhere?
Thx.

**Comment by K-Phoen** [comment]
It's in this repository :)

https://github.com/K-Phoen/dark/tree/master/cmd/converter
https://github.com/K-Phoen/dark/tree/master/internal/pkg/converter

**Comment by sfrank-mc** [comment]
Thanks!
