### ISSUE TITLE
skip certificate check

### ISSUE THREAD

**Issue by diskmanti** [K-Phoen/dark#64]
Hello,

I have deployed dark on a k8s cluster and I am self hosting my grafana instance.
Since grafana is exposed with a self signed cert dark is throwing this error:
```
'Warning' reason: 'Not synced' could not create dashboard from spec: could not find or create folder: Get "https://adc.com/api/folders?limit=100":  x509: certificate signed by unknown authority
```

Is there anyway to pass a flag to skip checking the certificates?

Thank you

**Comment by K-Phoen** [comment]
There isn't for now, but that would be an appreciated contribution :)
